#!/bin/bash

#https://www.jamf.com/jamf-nation/third-party-products/files/1051/install-latest-zoom-client

# this is the full URL
url="https://zoom.us/client/latest/ZoomInstallerIT.pkg"

# change directory to /private/tmp to make this the working directory
cd /private/tmp/

# download the installer package and name it for the linkID
/usr/bin/curl -JL "$url" -o "ZoomInstallerIT.pkg"

# install the package
/usr/sbin/installer -pkg "ZoomInstallerIT.pkg" -target /

# remove the installer package when done
/bin/rm -f "ZoomInstallerIT.pkg"
sleep 10s && /usr/local/bin/jamf policy
sleep 10s && /usr/local/bin/jamf recon


exit 0
